import { PersonalInfo, TechStackItem, ExperienceItem, EducationItem, ProjectItem, AchievementItem } from '../types'

export const personal: PersonalInfo = {
  name: 'Ade Ramadhani Putra',
  title: 'Full Stack Developer & UI/UX Designer',
  avatar: '/images/portfolio/rama-x2.jpg',
  location: 'Sukabumi, Jawa Barat',
  email: 'aderamadhaniputra35@gmail.com',
  website: 'https://rama-x2.my.id',
  github: 'https://github.com/Rama-X2',
  linkedin: 'https://linkedin.com/in/rama-xd',
  instagram: 'https://instagram.com/rama_ext4',
}

export const techStackList: TechStackItem[] = [
  { name: 'HTML5', icon: 'html' },
  { name: 'CSS3', icon: 'css' },
  { name: 'JavaScript', icon: 'js' },
  { name: 'TypeScript', icon: 'ts' },
  { name: 'PHP', icon: 'php' },
  { name: 'C', icon: 'c' },
  { name: 'C++', icon: 'cpp' },
  { name: 'Java', icon: 'java' },
  { name: 'Python', icon: 'py' },
  { name: 'Next.js', icon: 'nextjs' },
  { name: 'React', icon: 'react' },
  { name: 'Vue.js', icon: 'vue' },
  { name: 'Svelte', icon: 'svelte' },
  { name: 'Node.js', icon: 'nodejs' },
  { name: 'Express', icon: 'express' },
  { name: 'Tailwind CSS', icon: 'tailwind' },
  { name: 'MongoDB', icon: 'mongodb' },
  { name: 'MySQL', icon: 'mysql' },
  { name: 'Linux Kernel', icon: 'linux' },
  { name: 'Docker', icon: 'docker' },
  { name: 'NestJS', icon: 'nestjs' },
  { name: 'Git', icon: 'git' },
  { name: 'Arch Linux', icon: 'arch' },
  { name: 'Android SDK', icon: 'android' },
  { name: 'VS Code', icon: 'vscode' },
  { name: 'Sublime Text', icon: 'sublime' },
  { name: 'Figma', icon: 'figma' },
]

export const experiences: ExperienceItem[] = [
  {
    position: 'Full Stack Developer & Systems Designer',
    positionEn: 'Full Stack Developer & Systems Designer',
    period: '2023 – Sekarang',
    periodEn: '2023 – Present',
    color: '#6366f1',
    descriptions: [
      'Merancang dan membangun aplikasi web berkinerja tinggi menggunakan Next.js, React, dan TypeScript.',
      'Mengembangkan RESTful API scalable dan manajemen database terintegrasi.',
      'Mengimplementasikan desain UI/UX responsif, modern, dan bernuansa premium.',
    ],
    descriptionsEn: [
      'Designed and built high-performance web applications using Next.js, React, and TypeScript.',
      'Developed scalable RESTful APIs and integrated database management systems.',
      'Implemented responsive, modern, and premium UI/UX designs.',
    ],
  },
  {
    position: 'Linux Kernel & Android Customization',
    positionEn: 'Linux Kernel & Android Customization Specialist',
    period: '2022 – Sekarang',
    periodEn: '2022 – Present',
    color: '#10b981',
    descriptions: [
      'Kustomisasi kernel Linux, optimasi governor CPU/GPU, dan tuning performa I/O.',
      'Pengembangan custom ROM berbasis AOSP dan integrasi modul Android.',
    ],
    descriptionsEn: [
      'Linux kernel customization, CPU/GPU governor optimization, and I/O performance tuning.',
      'AOSP-based custom ROM development and Android module integration.',
    ],
  },
  {
    position: 'UI/UX Designer',
    positionEn: 'UI/UX Designer',
    period: '2023 – Sekarang',
    periodEn: '2023 – Present',
    color: '#06b6d4',
    descriptions: [
      'Membuat wireframe, kaji antarmuka pengguna, dan prototipe interaktif menggunakan Figma.',
      'Memastikan konsistensi sistem desain, aksesibilitas, dan kenyamanan pengguna.',
    ],
    descriptionsEn: [
      'Created wireframes, user interface studies, and interactive prototypes using Figma.',
      'Ensured design system consistency, accessibility, and user comfort.',
    ],
  },
]

export const education: EducationItem[] = [
  {
    institution: 'Universitas Linggabuana PGRI Sukabumi',
    degree: 'S1 Teknik Informatika',
    degreeEn: 'B.S. in Informatics Engineering',
    period: 'Sedang Berjalan',
    periodEn: 'Ongoing',
    location: 'Sukabumi, Jawa Barat',
    locationEn: 'Sukabumi, West Java',
    logo: '/logo-kampus/logo-kampus.jpeg',
    ongoing: true,
  },
  {
    institution: 'MA Al-Ma\'arij Hegarmanah',
    degree: 'IPS',
    degreeEn: 'Social Sciences (IPS)',
    period: '2021 – 2024',
    periodEn: '2021 – 2024',
    location: 'Sukabumi, Jawa Barat',
    locationEn: 'Sukabumi, West Java',
    logo: null,
    ongoing: false,
  },
]

export const achievements: AchievementItem[] = [
  {
    id: 1,
    title: 'Cisco Networking Academy – Ethical Hacker',
    issuer: 'Cisco Networking Academy',
    date: '22 Juli 2026',
    dateEn: 'July 22, 2026',
    image: '/gambar-sertifikat/cisco-ethical-hacker-certificate.png',
    verifyUrl: 'https://www.credly.com/badges/d6d1ef95-849b-4e56-8501-a7b67c7574e9/public_url',
  },
  {
    id: 2,
    title: 'Cisco Networking Academy – Introduction to Cybersecurity',
    issuer: 'Cisco Networking Academy',
    date: '20 Juli 2026',
    dateEn: 'July 20, 2026',
    image: '/gambar-sertifikat/cisco-intro-cybersecurity-certificate.png',
    verifyUrl: 'https://www.credly.com/badges/6ee1a4bb-bd90-482a-aef2-2a5433d710db/public_url',
  },
  {
    id: 3,
    title: 'Cisco Networking Academy – Networking Basics',
    issuer: 'Cisco Networking Academy',
    date: '20 Juli 2026',
    dateEn: 'July 20, 2026',
    image: '/gambar-sertifikat/cisco-networking-basics-certificate.png',
    verifyUrl: 'https://www.credly.com/badges/8c8ab9c0-6202-4bb3-a3d8-21d3f9f3ef4d/public_url',
  },
  {
    id: 4,
    title: 'DevCoach #200: Integrasi IT & AI powered by Asah!',
    issuer: 'DevCoach x Asah!',
    date: '26 Juni 2025',
    dateEn: 'June 26, 2025',
    image: '/gambar-sertifikat/devcoach-200.png',
    verifyUrl: 'https://www.dicoding.com/certificates/N9ZO5WO10PG5',
  },
  {
    id: 5,
    title: 'IDCamp x Dicoding Live #10 – UiPath Agentic Automation: Introduction and Use Case',
    issuer: 'Indosat Ooredoo Hutchison Digital Camp',
    date: '10 Juli 2025',
    dateEn: 'July 10, 2025',
    image: '/gambar-sertifikat/idcamp-live-10.png',
    verifyUrl: 'https://www.dicoding.com/certificates/KZX72V6NWX68',
  },
  {
    id: 6,
    title: 'IDCamp Alumni Dialogue #5 – Debunking the Myth of Intelligent Automation: Prepare for the Future Workforce',
    issuer: 'Indosat Ooredoo Hutchison Digital Camp',
    date: '22 Juli 2025',
    dateEn: 'July 22, 2025',
    image: '/gambar-sertifikat/idcamp-dialogue-5.png',
    verifyUrl: 'https://www.dicoding.com/certificates/N9ZO51N20PG5',
  },
]

export const projects: ProjectItem[] = [
  {
    id: 1,
    title: 'BumiTani – Premium Agricultural E-Commerce',
    description: 'Website e-commerce pertanian modern premium dengan database 72 produk (bibit, nutrisi, pakan, peralatan, pestisida, dan pupuk) dalam 6 kategori. Dilengkapi filter dan pencarian real-time, detail modal produk, sistem keranjang LocalStorage, serta checkout via WhatsApp.',
    descriptionEn: 'Modern premium agricultural e-commerce website featuring a 72-product database across 6 categories. Equipped with real-time search & filters, product detail modals, LocalStorage cart system, and WhatsApp checkout.',
    category: 'Web Development',
    technologies: ['HTML', 'Tailwind CSS', 'JavaScript', 'LocalStorage'],
    image: '/gambar-project/bumitani.png',
    liveDemoUrl: 'https://bumitani.server.my.id/',
    sourceCodeUrl: 'https://github.com/Rama-X2/bumitani-ecommerce',
    featured: true,
  },
  {
    id: 2,
    title: 'HomeLab – Premium Powder Drink E-Commerce',
    description: 'Platform e-commerce dan editorial web premium yang dirancang khusus untuk mempresentasikan lini produk bubuk minuman premium. Fokus pada estetika high-end, performa ringan tanpa overhead framework berat, serta pengalaman belanja (UI/UX) yang seamless.',
    descriptionEn: 'Premium powder drink e-commerce platform featuring high-end aesthetics, lightweight performance, and a seamless shopping experience.',
    category: 'Web Development',
    technologies: ['HTML', 'Tailwind CSS', 'JavaScript', 'LocalStorage'],
    image: '/gambar-project/homelab.jpg',
    liveDemoUrl: 'https://homelab.server.my.id/',
    sourceCodeUrl: 'https://github.com/Rama-X2/homelab-ecommerce',
    featured: true,
  },
  {
    id: 3,
    title: 'Rama Store – Gaming Topup Platform',
    description: 'Modern gaming top-up platform dengan real-time transaction processing, multi-game support, dan animasi yang menarik. Dibangun menggunakan Next.js, TypeScript, dan Framer Motion.',
    descriptionEn: 'Modern gaming top-up platform with real-time transaction processing, multi-game support, and engaging animations built using Next.js, TypeScript, and Framer Motion.',
    category: 'Web Development',
    technologies: ['Next.js', 'TypeScript', 'Framer Motion', 'Tailwind CSS'],
    image: '/gambar-project/rama-store.png',
    liveDemoUrl: 'https://store.rama-x2.my.id/',
    sourceCodeUrl: 'https://github.com/Rama-X2/rama-store',
    featured: true,
  },
  {
    id: 4,
    title: 'Custom ROM by Rama – Basic AOSP',
    description: 'ROM custom ringan berbasis Android 15 (Vanilla Ice Cream) yang disempurnakan dengan asisten AI cerdas menggunakan TensorFlow dan NLP. Menawarkan pengalaman Android murni yang responsif, hemat baterai, dan efisien.',
    descriptionEn: 'Lightweight Android 15 (Vanilla Ice Cream) custom ROM enhanced with AI assistant using TensorFlow & NLP for pure performance.',
    category: 'Operating System',
    technologies: ['AOSP', 'Android 15', 'Shell Script', 'Python'],
    image: '/gambar-project/custom-rom-aosp.png',
    sourceCodeUrl: 'https://github.com/Rama-X2',
    featured: true,
  },
  {
    id: 5,
    title: 'Kernel Overclocking by Rama',
    description: 'Project kustomisasi kernel dengan fokus pada overclocking CPU/GPU, governor tuning, serta optimasi I/O scheduler. Menghasilkan peningkatan performa perangkat hingga 25% tanpa mengorbankan stabilitas sistem.',
    descriptionEn: 'Kernel customization focused on CPU/GPU overclocking, governor tuning, and I/O scheduler optimization boosting performance by 25%.',
    category: 'Operating System',
    technologies: ['Android SDK', 'Shell Script', 'Linux Kernel', 'C'],
    image: '/gambar-project/kernel-overclocking.png',
    sourceCodeUrl: 'https://github.com/Rama-X2',
  },
]

export const translations = {
  id: {
    nav: {
      home: 'Beranda',
      about: 'Tentang',
      projects: 'Proyek',
      achievements: 'Prestasi',
      contact: 'Kontak',
    },
    personal: {
      greeting: 'Halo, saya',
      bio: 'Seorang Full Stack Developer dan UI/UX Designer yang aktif mengembangkan berbagai solusi digital modern, mulai dari website, software, hingga sistem berbasis performa tinggi. Memiliki ketertarikan besar pada web development, server management, dan optimasi sistem, dengan fokus menciptakan aplikasi yang responsif, efisien, dan nyaman digunakan.',
      location: 'Sukabumi, Jawa Barat',
      available: 'Tersedia untuk peluang baru',
      viewResume: 'Lihat Resume',
      contactMe: 'Hubungi Saya',
    },
    quickCards: {
      about: { label: 'Tentang Saya', sub: 'Siapa saya' },
      projects: { label: 'Proyek Saya', sub: 'Karya & portofolio' },
      achievements: { label: 'Prestasi & Sertifikat', sub: 'Sertifikat & penghargaan' },
      contact: { label: 'Kontak', sub: 'Hubungi saya' },
    },
    skillsTitle: 'Tech Stack',
    aboutSec: {
      title: 'Tentang Saya',
      experienceTitle: 'Pengalaman',
      educationTitle: 'Pendidikan',
      ongoing: 'Sedang Berjalan',
    },
    achievementsSec: {
      title: 'Prestasi & Sertifikat',
      subtitle: 'Sertifikat & penghargaan yang telah saya raih',
      clickToView: 'Klik untuk lihat sertifikat',
    },
    projectsSec: {
      title: 'Proyek Saya',
      subtitle: 'Koleksi proyek yang pernah saya kerjakan',
      featured: 'Unggulan',
      technologies: 'Tech Stack',
      liveDemo: 'Live Demo',
      sourceCode: 'Source Code',
    },
    contactSec: {
      tag: 'HUBUNGI SAYA',
      heading: 'Mari Berdiskusi!',
      description: 'Punya proyek menarik, ingin berkolaborasi, atau sekadar berdiskusi? Jangan ragu untuk menghubungi saya! Saya akan berusaha membalas secepat mungkin.',
      locationTag: 'LOKASI & JANGKAUAN',
      locationHeading: 'Sukabumi, Jawa Barat',
      locationDesc: 'Berbasis di Sukabumi, Jawa Barat. Siap bekerja secara remote (jarak jauh) untuk klien dari seluruh dunia maupun on-site untuk proyek lokal.',
      openMaps: 'Buka di Google Maps',
      socialsTag: 'MEDIA SOSIAL',
      socialsHeading: 'Temukan Saya Di',
      formTag: 'PESAN INSTAN',
      formHeading: 'Kirim Pesan Instan',
      formDesc: 'Gunakan formulir di bawah ini untuk mengirimkan pesan secara instan. Semua masukan Anda sangat berarti bagi saya.',
      fullName: 'Nama Lengkap',
      fullNamePlaceholder: 'Nama Anda',
      emailAddress: 'Alamat Email',
      emailPlaceholder: 'Email Anda',
      subject: 'Subjek',
      subjectPlaceholder: 'Apa subjek pesan Anda?',
      message: 'Isi Pesan',
      messagePlaceholder: 'Tuliskan pesan Anda di sini...',
      sendMessage: 'Kirim Pesan Instan',
      sending: 'Mengirim...',
      successMsg: 'Pesan Anda berhasil terkirim! Terima kasih telah menghubungi saya.',
    },
    resumeModal: {
      downloadPdf: 'Unduh CV (PDF)',
      close: 'Tutup',
    },
  },
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      projects: 'Projects',
      achievements: 'Achievements',
      contact: 'Contact',
    },
    personal: {
      greeting: "Hello, I'm",
      bio: 'A Full Stack Developer and UI/UX Designer who actively develops modern digital solutions, ranging from websites, software, to high-performance systems. Passionate about web development, server management, and system optimization, focusing on creating responsive, efficient, and user-friendly applications.',
      location: 'Sukabumi, West Java',
      available: 'Available for opportunities',
      viewResume: 'View Resume',
      contactMe: 'Contact Me',
    },
    quickCards: {
      about: { label: 'About Me', sub: 'Who I am' },
      projects: { label: 'My Projects', sub: 'Works & portfolio' },
      achievements: { label: 'Achievements', sub: 'Certificates & awards' },
      contact: { label: 'Contact', sub: 'Get in touch' },
    },
    skillsTitle: 'Tech Stack',
    aboutSec: {
      title: 'About Me',
      experienceTitle: 'Experience',
      educationTitle: 'Education',
      ongoing: 'Ongoing',
    },
    achievementsSec: {
      title: 'Achievements & Certificates',
      subtitle: 'Certificates and awards I have earned',
      clickToView: 'Click to view certificate',
    },
    projectsSec: {
      title: 'My Projects',
      subtitle: 'A showcase of projects I have built',
      featured: 'Featured',
      technologies: 'Tech Stack',
      liveDemo: 'Live Demo',
      sourceCode: 'Source Code',
    },
    contactSec: {
      tag: 'CONTACT ME',
      heading: "Let's Connect!",
      description: 'Have an interesting project, want to collaborate, or just say hi? Feel free to reach out to me! I will do my best to respond as soon as possible.',
      locationTag: 'LOCATION & REACH',
      locationHeading: 'Sukabumi, West Java',
      locationDesc: 'Based in Sukabumi, West Java. Open for remote work worldwide as well as on-site for local projects.',
      openMaps: 'Open in Google Maps',
      socialsTag: 'SOCIAL MEDIA',
      socialsHeading: 'Find Me On',
      formTag: 'INSTANT MESSAGE',
      formHeading: 'Send Instant Message',
      formDesc: 'Use the form below to send me a message directly. All input is greatly appreciated.',
      fullName: 'Full Name',
      fullNamePlaceholder: 'Your Name',
      emailAddress: 'Email Address',
      emailPlaceholder: 'Your Email',
      subject: 'Subject',
      subjectPlaceholder: 'What is the subject of your message?',
      message: 'Message',
      messagePlaceholder: 'Write your message here...',
      sendMessage: 'Send Instant Message',
      sending: 'Sending...',
      successMsg: 'Your message has been sent successfully! Thank you for reaching out.',
    },
    resumeModal: {
      downloadPdf: 'Download CV (PDF)',
      close: 'Close',
    },
  },
}
